Allow user to specify number of itineraries
thecristen/open_trip_planner_client pull request #5
Opened 2024-10-23 20:55 UTC by joshlarson

This keeps the default at 5, but allows the caller to specify whatever number of itineraries they want.

Rationale: If the next 5 trips from point A to point B include one on the Park St --> Copley branch, one with the C branch and one with the D branch then we'll erroneously say C/D, rather than the more accurate B/C/D/E. Getting some much larger number of trips (like 40, or 100, or something) would keep us from leaving out relevant trips, and it would be nice to iterate on exactly how many trips to get from OTP without having to cut a release each time.

Also, Ye Olde Trip Planner probably still wants 5 trips.

2024-10-23 22:30 UTC, thecristen approved these changes
works for me!

2024-10-24 21:07 UTC, thecristen requested changes

2024-10-24 21:07 UTC, thecristen commented on lib/open_trip_planner_client/plan_params.ex
Hey @joshlarson can you add the `numItineraries` to the `@type t` part too? (around line 104 in this file). Just missed that my first review

2024-10-30 18:26 UTC, joshlarson commented on lib/open_trip_planner_client/plan_params.ex
@thecristen - [Like so](https://github.com/thecristen/open_trip_planner_client/pull/5/commits/6bf7e74657bddea1eb488029d54a942daa678397)?

2024-10-31 02:54 UTC, thecristen approved these changes

2024-12-03 19:35 UTC, joshlarson commented
Superceded by:
- https://github.com/mbta/open_trip_planner_client/pull/2

2024-12-03 19:35 UTC, closed without merging